// ── parlc: Parlance compiler ─────────────────────────────────────
//
//  Usage:
//   parlance  <file.plc>                           compile and show bytecode
//   parlance  <file.plc> --tokens                  show tokens (lexer output)
//   parlance  <file.plc> --ast                     show parsed AST
//   parlance  <file.plc> --ir                      show IR
//   parlance  <file.plc> --opt                     show optimized IR
//   parlance  <file.plc> --bytecode                show generated bytecode
//   parlance  <file.plc> --lua                      emit self-contained Lua source
//   parlance  <file.plc> --lua -o <out.lua>         write Lua source to file
//   parlance  <file.plc> --run                     compile and run (via GraftVM)
//   parlance  <file.plc> --run --entry main        run with "main" as entry point
//   parlance  <file.plc> -o <out.bc>               write bytecode to file

use std::env;
use std::fs;
use std::path::PathBuf;
use std::process;

use graftvm_interpreter::vm::VM;
use graftvm_liternal::Liternal;
use parlance_codegen::nfi::NativeRegistry;
use parlance_optimize::optimize;
use parlance_parser::ast::Stmt;
use parlance_typecheck::typecheck;

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 2 {
        eprintln!(
            "Usage: parlance <file.plc> [--tokens|--ast|--ir|--opt|--bytecode|--lua|--run] [--entry <name>] [-o <out.bc>]"
        );
        process::exit(1);
    }

    // ── Parse CLI flags ─────────────────────────────────────────
    let mut entry_point: Option<String> = None;
    let mut flags: Vec<String> = Vec::new();
    let mut i = 2;
    while i < args.len() {
        match args[i].as_str() {
            "--entry" => {
                i += 1;
                entry_point = Some(args.get(i).cloned().unwrap_or_else(|| {
                    eprintln!("error: --entry requires a function name");
                    process::exit(1);
                }));
            }
            other => flags.push(other.to_string()),
        }
        i += 1;
    }
    let flag = |name: &str| flags.contains(&name.to_string());

    // ── Set up search paths for std library ──────────────────────
    let std_dir = if let Ok(exe) = env::current_exe() {
        if let Some(dir) = exe.parent() {
            let p = dir.join("std");
            if p.is_dir() { p } else { PathBuf::from("std") }
        } else {
            PathBuf::from("std")
        }
    } else {
        PathBuf::from("std")
    };
    parlance_import::set_search_paths(vec![
        std_dir.clone(),
        PathBuf::from("std"),
    ]);

    let path = &args[1];
    let raw_source = match fs::read_to_string(path) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("error: cannot read '{}': {}", path, e);
            process::exit(1);
        }
    };

    // ── Automatically prepend prelude ────────────────────────────
    let prelude = (|| -> Option<String> {
        for dir in [PathBuf::from("std"), std_dir.clone()] {
            let path = dir.join("prelude.plc");
            if let Ok(content) = fs::read_to_string(&path) {
                return Some(content);
            }
        }
        eprintln!("warning: std/prelude.plc not found");
        None
    })();
    let source = match prelude {
        Some(p) => format!("{}\n{}", p, raw_source),
        None => raw_source.clone(),
    };

    if flag("--tokens") {
        show_tokens(&source);
        return;
    }

    let (stmts, prec) = match parlance_parser::parse_program(&source) {
        Ok(r) => r,
        Err(e) => {
            eprintln!("parse error: {e}");
            process::exit(1);
        }
    };

    if flag("--ast") {
        show_ast(&stmts, &prec);
        return;
    }

    // Run semantic analysis
    let semant_result = match parlance_semant::analyze(stmts) {
        Ok(r) => r,
        Err(e) => {
            eprintln!("semantic error: {}", e.msg);
            process::exit(1);
        }
    };

    // ── Type checking ──────────────────────────────────────────
    if let Err(e) = typecheck(&semant_result) {
        eprintln!("type error: {}", e.msg);
        process::exit(1);
    }

    // Lower to IR
    let ir = parlance_ir::lower_program(&semant_result);
    if flag("--ir") {
        println!("{}", parlance_ir::dump(&ir));
        return;
    }

    // Optimize
    let optimized = optimize(&ir);
    if flag("--opt") {
        println!("{}", parlance_ir::dump(&optimized));
        return;
    }

    // ── Determine entry point ───────────────────────────────────
    let do_run = flag("--run");
    let do_lua = flag("--lua");
    let entry = entry_point.or_else(|| if do_run || do_lua { Some("main".into()) } else { None });
    let entry_ref = entry.as_deref();

    // ── Lua backend ─────────────────────────────────────────────
    if do_lua {
        let lua_source = parlance_lua::compile(&optimized, entry_ref);
        if let Some(pos) = args.iter().position(|a| a == "-o") {
            if let Some(out_path) = args.get(pos + 1) {
                if let Err(e) = fs::write(out_path, &lua_source) {
                    eprintln!("error: cannot write '{}': {}", out_path, e);
                    process::exit(1);
                }
                println!("wrote lua source to '{}'", out_path);
            }
        } else {
            println!("{}", lua_source);
        }
        return;
    }

    // ── Build native registry from IR ────────────────────────────
    let nfi = NativeRegistry::from_ir(&optimized);

    // Codegen
    let bytecode = parlance_codegen::compile_with(&optimized, entry_ref, &nfi);

    if flag("--bytecode") || (!flag("-o") && !do_run && !args.contains(&"-o".to_string())) {
        show_bytecode(&bytecode);
        return;
    }

    if do_run {
        run_bytecode(&bytecode, &nfi);
        return;
    }

    if let Some(pos) = args.iter().position(|a| a == "-o") {
        if let Some(out_path) = args.get(pos + 1) {
            let dump: String = bytecode
                .iter()
                .map(|op| format!("{op:?}"))
                .collect::<Vec<_>>()
                .join("\n");
            if let Err(e) = fs::write(out_path, &dump) {
                eprintln!("error: cannot write '{}': {}", out_path, e);
                process::exit(1);
            }
            println!("wrote {} instructions to '{}'", bytecode.len(), out_path);
        }
    }
}

fn show_tokens(source: &str) {
    match parlance_lexer::tokenize(source) {
        Ok(tokens) => {
            for t in &tokens {
                println!("{:>4}:{:<4}  {}", t.line, t.col, t.token);
            }
        }
        Err(e) => {
            eprintln!("lex error: {e}");
            process::exit(1);
        }
    }
}

fn show_ast(stmts: &[Stmt], prec: &std::collections::HashMap<String, u32>) {
    for s in stmts {
        println!("{s}");
    }
    if !prec.is_empty() {
        println!("\n-- operator precedence --");
        let mut ops: Vec<_> = prec.iter().collect();
        ops.sort_by_key(|(_, &bp)| std::cmp::Reverse(bp));
        for (op, bp) in ops {
            println!("  {op:>4}  BP = {bp}");
        }
    }
}

fn show_bytecode(bc: &[graftvm_bytecode::Opcode]) {
    println!(";; bytecode ({} instructions)", bc.len());
    for (i, op) in bc.iter().enumerate() {
        println!("  {:>4}:  {op:?}", i);
    }
}

/// Register the default native function implementations with the VM
/// and run the bytecode.
fn run_bytecode(bc: &[graftvm_bytecode::Opcode], nfi: &NativeRegistry) {
    let mut vm = VM::new(bc.to_vec());

    // Register native function implementations.
    // These are called at runtime via the CallNative opcode.
    for name in nfi.all_names() {
        match name.as_str() {
            "print" => {
                vm.register_native("print", |args| {
                    println!("{}", args[0]);
                    Ok(args[0].clone())
                });
            }
            "add" => {
                vm.register_native("add", |args| {
                    let x = args[0].expect_int()?.expect_i64()?;
                    let y = args[1].expect_int()?.expect_i64()?;
                    Ok(Liternal::from(x + y))
                });
            }
            "sub" => {
                vm.register_native("sub", |args| {
                    let x = args[0].expect_int()?.expect_i64()?;
                    let y = args[1].expect_int()?.expect_i64()?;
                    Ok(Liternal::from(x - y))
                });
            }
            "mul" => {
                vm.register_native("mul", |args| {
                    let x = args[0].expect_int()?.expect_i64()?;
                    let y = args[1].expect_int()?.expect_i64()?;
                    Ok(Liternal::from(x * y))
                });
            }
            "div" => {
                vm.register_native("div", |args| {
                    let x = args[0].expect_int()?.expect_i64()?;
                    let y = args[1].expect_int()?.expect_i64()?;
                    Ok(Liternal::from(x / y))
                });
            }
            _ => {
                eprintln!("warning: no native implementation for '{}'", name);
            }
        }
    }

    println!(";; running bytecode ({} instructions)...", bc.len());
    match vm.run_debug() {
        Ok(()) => println!(";; execution finished"),
        Err(e) => eprintln!("runtime error: {e}"),
    }
}
