// ── parlc: Parlance compiler ─────────────────────────────────────
//
//  Usage:
//   parlance  <file.plc>               compile and show bytecode
//   parlance  <file.plc> --tokens      show tokens (lexer output)
//   parlance  <file.plc> --ast         show parsed AST
//   parlance  <file.plc> --ir          show IR
//   parlance  <file.plc> --opt         show optimized IR
//   parlance  <file.plc> --bytecode    show generated bytecode
//   parlance  <file.plc> --run         compile and run (via GraftVM)
//   parlance  <file.plc> -o <out.bc>   write bytecode to file

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process;

use graftvm_interpreter::vm::VM;
use parlance_optimize::optimize;
use parlance_parser::ast::Stmt;

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 2 {
        eprintln!(
            "Usage: parlance <file.plc> [--tokens|--ast|--ir|--opt|--bytecode|--run] [-o <out.bc>]"
        );
        process::exit(1);
    }

    // ── Set up search paths for std library ──────────────────────
    let std_dir = if let Ok(exe) = env::current_exe() {
        if let Some(dir) = exe.parent() {
            let p = dir.join("std");
            if p.is_dir() { p } else { PathBuf::from("std") }
        } else {
            PathBuf::from("std")
        }
    } else {
        PathBuf::from("std")
    };
    parlance_import::set_search_paths(vec![
        std_dir.clone(),
        // fallback: current working directory
        PathBuf::from("std"),
    ]);

    let path = &args[1];
    let raw_source = match fs::read_to_string(path) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("error: cannot read '{}': {}", path, e);
            process::exit(1);
        }
    };

    // ── Automatically prepend prelude ────────────────────────────
    // Reads std/prelude.plc and inlines its content before parsing.
    // This ensures infix declarations are visible to the Pratt parser
    // before it encounters user expressions that use those operators.
    let prelude = (|| -> Option<String> {
        // Try multiple locations for the std/ directory
        for dir in [PathBuf::from("std"), std_dir.clone()] {
            let path = dir.join("prelude.plc");
            if let Ok(content) = fs::read_to_string(&path) {
                return Some(content);
            }
        }
        eprintln!("warning: std/prelude.plc not found — compiling without prelude");
        None
    })();
    let source = match prelude {
        Some(p) => format!("{}\n{}", p, raw_source),
        None => raw_source.clone(),
    };

    let flags: Vec<&str> = args.iter().skip(2).map(|s| s.as_str()).collect();
    let flag = |name: &str| flags.contains(&name);

    if flag("--tokens") {
        show_tokens(&source);
        return;
    }

    let (stmts, prec) = match parlance_parser::parse_program(&source) {
        Ok(r) => r,
        Err(e) => {
            eprintln!("parse error: {e}");
            process::exit(1);
        }
    };

    if flag("--ast") {
        show_ast(&stmts, &prec);
        return;
    }

    // Run semantic analysis
    let semant_result = match parlance_semant::analyze(stmts) {
        Ok(r) => r,
        Err(e) => {
            eprintln!("semantic error: {}", e.msg);
            process::exit(1);
        }
    };

    // Lower to IR
    let ir = parlance_ir::lower_program(&semant_result);
    if flag("--ir") {
        println!("{}", parlance_ir::dump(&ir));
        return;
    }

    // Optimize
    let optimized = optimize(&ir);
    if flag("--opt") {
        println!("{}", parlance_ir::dump(&optimized));
        return;
    }

    // Codegen
    let stem = Path::new(path)
        .file_stem()
        .unwrap()
        .to_str()
        .unwrap_or("out");
    let bytecode = parlance_codegen::compile_program(&optimized, stem);

    // Flags that need bytecode
    if flag("--bytecode") || (!flag("-o") && !flag("--run") && !args.contains(&"-o".to_string())) {
        show_bytecode(&bytecode);
        return;
    }

    if flag("--run") {
        run_bytecode(&bytecode);
        return;
    }

    if let Some(pos) = args.iter().position(|a| a == "-o") {
        if let Some(out_path) = args.get(pos + 1) {
            let dump: String = bytecode
                .iter()
                .map(|op| format!("{op:?}"))
                .collect::<Vec<_>>()
                .join("\n");
            if let Err(e) = fs::write(out_path, &dump) {
                eprintln!("error: cannot write '{}': {}", out_path, e);
                process::exit(1);
            }
            println!("wrote {} instructions to '{}'", bytecode.len(), out_path);
        }
    }
}

fn show_tokens(source: &str) {
    match parlance_lexer::tokenize(source) {
        Ok(tokens) => {
            for t in &tokens {
                println!("{:>4}:{:<4}  {}", t.line, t.col, t.token);
            }
        }
        Err(e) => {
            eprintln!("lex error: {e}");
            process::exit(1);
        }
    }
}

fn show_ast(stmts: &[Stmt], prec: &std::collections::HashMap<String, u32>) {
    for s in stmts {
        println!("{s}");
    }
    if !prec.is_empty() {
        println!("\n-- operator precedence --");
        let mut ops: Vec<_> = prec.iter().collect();
        ops.sort_by_key(|(_, &bp)| std::cmp::Reverse(bp));
        for (op, bp) in ops {
            println!("  {op:>4}  BP = {bp}");
        }
    }
}

fn show_bytecode(bc: &[graftvm_bytecode::Opcode]) {
    println!(";; bytecode ({} instructions)", bc.len());
    for (i, op) in bc.iter().enumerate() {
        println!("  {:>4}:  {op:?}", i);
    }
}

fn run_bytecode(bc: &[graftvm_bytecode::Opcode]) {
    let mut vm = VM::new(bc.to_vec());
    println!(";; running bytecode ({} instructions)...", bc.len());
    match vm.run_debug() {
        Ok(()) => println!(";; execution finished"),
        Err(e) => eprintln!("runtime error: {e}"),
    }
}
